# Generated by Django 4.1.3 on 2023-02-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agents',
        ),
    ]
