# Generated by Django 4.1.3 on 2023-02-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0005_photo_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
