# Generated by Django 4.1.3 on 2023-02-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Loacation',
            new_name='Location',
        ),
    ]
