# Generated by Django 4.1.3 on 2023-02-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0008_rename_loacation_listing_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
